name: project_fireborn
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bonfire: ^1.1.3
  cupertino_icons: ^1.0.2
  flame: ^1.0.0-rc1
  flame_audio: ^1.0.0-rc.1
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/items/
    - assets/images/female/
    - assets/images/female/Idle/
    - assets/images/female/Walk/
    - assets/images/female/Attack/
    - assets/images/female/Shield/
    - assets/images/male/
    - assets/images/male/Idle/
    - assets/images/male/Walk/
    - assets/images/male/Attack/
    - assets/images/male/Shield/
    - assets/images/tiled/